// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/is/v1/comment-service/add": {
            "post": {
                "description": "insert into table comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMENT SERVICE"
                ],
                "summary": "AddComment",
                "operationId": "AddComment",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-domain_AddCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-domain_AddCommentResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/comment-service/get-comment": {
            "post": {
                "description": "select * from table comment where productID = :1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMENT SERVICE"
                ],
                "summary": "GetComment",
                "operationId": "GetComment",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-domain_GetCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-domain_GetCommentResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AddCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "productId",
                "rating",
                "userId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "domain.AddCommentResponse": {
            "type": "object"
        },
        "domain.GetCommentRequest": {
            "type": "object",
            "required": [
                "productId"
            ],
            "properties": {
                "filter": {
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                },
                "productId": {
                    "type": "string"
                },
                "sort": {
                    "type": "string"
                }
            }
        },
        "domain.GetCommentResponse": {
            "type": "object",
            "required": [
                "comments"
            ],
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GetCommentResponseDetail"
                    }
                }
            }
        },
        "domain.GetCommentResponseDetail": {
            "type": "object",
            "required": [
                "content",
                "rating",
                "timestamp",
                "userImage",
                "username"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "userImage": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "transport.Request-domain_AddCommentRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.AddCommentRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-domain_GetCommentRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetCommentRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-domain_AddCommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.AddCommentResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-domain_GetCommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetCommentResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "transport.Trace": {
            "type": "object",
            "required": [
                "cid",
                "cts"
            ],
            "properties": {
                "cid": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "cts": {
                    "type": "integer"
                },
                "dur": {
                    "type": "integer"
                },
                "frm": {
                    "type": "string"
                },
                "replyTo": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "sts": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                },
                "transactionTimeout": {
                    "type": "integer",
                    "maximum": 120000
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
