CREATE TABLE public."CART_ITEM" (
	"CART_ITEM_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"USER_ID" uuid NOT NULL,
	"PRODUCT_ID" uuid NOT NULL,
	"CART_ITEM_QUANTITY" numeric NOT NULL,
	"CREATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "CART_ITEM_pkey" PRIMARY KEY ("CART_ITEM_ID"),
    CONSTRAINT unique_cart_item_product UNIQUE ("USER_ID", "PRODUCT_ID")
);

CREATE TABLE public."OUTBOX" (
	"AGGREGATE_ID" uuid NOT NULL,
	"COMMAND_ID" uuid NOT NULL,
	"COMMAND_TYPE" varchar(255) NOT NULL,
	"PAYLOAD" text NULL,
	"REPLY_TO" varchar(255) NULL,
	"TRACE_PARENT" varchar(100) NULL,
	CONSTRAINT "OUTBOX_pkey" PRIMARY KEY ("COMMAND_ID")
);

CREATE TABLE public."PRODUCT" (
	"PRODUCT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"PRODUCT_NAME" varchar(500) NOT NULL,
	"PRODUCT_DESCRIPTION" json NOT NULL,
	"PRODUCT_IMAGE" text NOT NULL,
	"PRODUCT_PRICE" varchar(20) NOT NULL,
	"CREATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"PRODUCT_CATEGORY" varchar(50) NOT NULL,
	"GENDER" varchar(10) NOT NULL,
	CONSTRAINT "PRODUCT_pkey" PRIMARY KEY ("PRODUCT_ID")
);