// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/is/v1/order-service/execute-transaction": {
            "post": {
                "description": "Delete all items on cart -\u003e minus quantity of product in cart service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "ExecuteTransaction",
                "operationId": "ExecuteTransaction",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-domain_ExecuteTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-domain_ExecuteTransactionResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/order-service/get-checkout-item": {
            "post": {
                "description": "Get the checkout item (cdc from cart table)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "GetCheckoutItem",
                "operationId": "GetCheckoutItem",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-domain_GetCheckoutItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-domain_GetCheckoutItemResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/order-service/get-history": {
            "post": {
                "description": "Show a history of purchased products from a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "GetPurchasedProducts",
                "operationId": "GetPurchasedProducts",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-domain_GetHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-domain_GetHistoryResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ExecuteTransactionRequest": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ExecuteTransactionRequestDetail"
                    }
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.ExecuteTransactionRequestDetail": {
            "type": "object",
            "properties": {
                "cartItemId": {
                    "type": "string"
                },
                "cartItemQuantity": {
                    "type": "integer"
                },
                "productCatergory": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "productPrice": {
                    "type": "number"
                }
            }
        },
        "domain.ExecuteTransactionResponse": {
            "type": "object"
        },
        "domain.GetCheckoutItemRequest": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.GetCheckoutItemResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GetCheckoutItemResponseDetail"
                    }
                }
            }
        },
        "domain.GetCheckoutItemResponseDetail": {
            "type": "object",
            "properties": {
                "pricePerUnit": {
                    "type": "number"
                },
                "productCatergory": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "productQuantity": {
                    "type": "integer"
                }
            }
        },
        "domain.GetHistoryRequest": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.GetHistoryResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GetHistoryResponseDetail"
                    }
                }
            }
        },
        "domain.GetHistoryResponseDetail": {
            "type": "object",
            "properties": {
                "deliveryStatus": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                }
            }
        },
        "transport.Request-domain_ExecuteTransactionRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.ExecuteTransactionRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-domain_GetCheckoutItemRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetCheckoutItemRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-domain_GetHistoryRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetHistoryRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-domain_ExecuteTransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.ExecuteTransactionResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-domain_GetCheckoutItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetCheckoutItemResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-domain_GetHistoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetHistoryResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "transport.Trace": {
            "type": "object",
            "required": [
                "cid",
                "cts"
            ],
            "properties": {
                "cid": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "cts": {
                    "type": "integer"
                },
                "dur": {
                    "type": "integer"
                },
                "frm": {
                    "type": "string"
                },
                "replyTo": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "sts": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                },
                "transactionTimeout": {
                    "type": "integer",
                    "maximum": 120000
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
