definitions:
  domain.ExecuteTransactionRequest:
    properties:
      details:
        items:
          $ref: '#/definitions/domain.ExecuteTransactionRequestDetail'
        type: array
      userID:
        type: string
    type: object
  domain.ExecuteTransactionRequestDetail:
    properties:
      cartItemId:
        type: string
      cartItemQuantity:
        type: integer
      productCatergory:
        type: string
      productId:
        type: string
      productImage:
        type: string
      productName:
        type: string
      productPrice:
        type: number
    type: object
  domain.ExecuteTransactionResponse:
    type: object
  domain.GetCheckoutItemRequest:
    properties:
      userID:
        type: string
    type: object
  domain.GetCheckoutItemResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/domain.GetCheckoutItemResponseDetail'
        type: array
    type: object
  domain.GetCheckoutItemResponseDetail:
    properties:
      pricePerUnit:
        type: number
      productCatergory:
        type: string
      productId:
        type: string
      productImage:
        type: string
      productName:
        type: string
      productQuantity:
        type: integer
    type: object
  domain.GetHistoryRequest:
    properties:
      userID:
        type: string
    type: object
  domain.GetHistoryResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/domain.GetHistoryResponseDetail'
        type: array
    type: object
  domain.GetHistoryResponseDetail:
    properties:
      deliveryStatus:
        type: string
      orderId:
        type: string
      paymentStatus:
        type: string
      productId:
        type: string
      productImage:
        type: string
      productName:
        type: string
    type: object
  transport.Request-domain_ExecuteTransactionRequest:
    properties:
      data:
        $ref: '#/definitions/domain.ExecuteTransactionRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Request-domain_GetCheckoutItemRequest:
    properties:
      data:
        $ref: '#/definitions/domain.GetCheckoutItemRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Request-domain_GetHistoryRequest:
    properties:
      data:
        $ref: '#/definitions/domain.GetHistoryRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Response-domain_ExecuteTransactionResponse:
    properties:
      data:
        $ref: '#/definitions/domain.ExecuteTransactionResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Response-domain_GetCheckoutItemResponse:
    properties:
      data:
        $ref: '#/definitions/domain.GetCheckoutItemResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Response-domain_GetHistoryResponse:
    properties:
      data:
        $ref: '#/definitions/domain.GetHistoryResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Result:
    properties:
      code:
        type: string
      details:
        type: object
      message:
        type: string
      statusCode:
        type: integer
    type: object
  transport.Trace:
    properties:
      cid:
        type: string
      clientId:
        type: string
      cts:
        type: integer
      dur:
        type: integer
      frm:
        type: string
      replyTo:
        type: string
      sid:
        type: string
      sts:
        type: integer
      to:
        type: string
      transactionTimeout:
        maximum: 120000
        type: integer
      userName:
        type: string
    required:
    - cid
    - cts
    type: object
info:
  contact: {}
paths:
  /is/v1/order-service/execute-transaction:
    post:
      consumes:
      - application/json
      description: Delete all items on cart -> minus quantity of product in cart service
      operationId: ExecuteTransaction
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_ExecuteTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_ExecuteTransactionResponse'
      summary: ExecuteTransaction
      tags:
      - ORDER SERVICE
  /is/v1/order-service/get-checkout-item:
    post:
      consumes:
      - application/json
      description: Get the checkout item (cdc from cart table)
      operationId: GetCheckoutItem
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_GetCheckoutItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_GetCheckoutItemResponse'
      summary: GetCheckoutItem
      tags:
      - ORDER SERVICE
  /is/v1/order-service/get-history:
    post:
      consumes:
      - application/json
      description: Show a history of purchased products from a user
      operationId: GetPurchasedProducts
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_GetHistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_GetHistoryResponse'
      summary: GetPurchasedProducts
      tags:
      - ORDER SERVICE
swagger: "2.0"
