CREATE TABLE public."CART_ITEM" (
	"CART_ITEM_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"USER_ID" uuid NOT NULL,
	"PRODUCT_ID" uuid NOT NULL,
	"CART_ITEM_QUANTITY" numeric NOT NULL,
	"CREATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "CART_ITEM_pkey" PRIMARY KEY ("CART_ITEM_ID")
);

CREATE TABLE public."ORDER_ITEM" (
	"ORDER_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"PRODUCT_ID" uuid NOT NULL,
	"USER_ID" uuid NOT NULL,
	"ORDER_STATUS" varchar(60) NOT NULL,
	"DELIVERY_STATUS" varchar(60) NOT NULL,
	"PAYMENT_STATUS" varchar(60) NOT NULL,
	"CREATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "ORDER_ITEM_pkey" PRIMARY KEY ("ORDER_ID")
);