CREATE TABLE public."CART_ITEM" (
	"CART_ITEM_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"USER_ID" uuid NOT NULL,
	"PRODUCT_ID" uuid NOT NULL,
	"CART_ITEM_QUANTITY" numeric NOT NULL,
	"CREATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "CART_ITEM_pkey" PRIMARY KEY ("CART_ITEM_ID")
);

CREATE TABLE public."ORDER_ITEM" (
    "ORDER_ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "PRODUCT_ID" UUID NOT NULL,
    "TRANSACTION_ID" UUID NOT NULL,
    "USER_ID" UUID NOT NULL,
    "DELIVERY_STATUS" VARCHAR(60) NOT NULL,
    "PAYMENT_STATUS" VARCHAR(60) NOT null,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "TRANSACTION" (
    "TRANSACTION_ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Assuming TRANSACTION_ID is unique
    "STATUS" VARCHAR(50) NOT NULL, -- To ensure only valid status values
    "PROCESSING" INT NOT NULL, -- Integer to store processing status
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Auto-populate with current timestamp
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."PRODUCT" (
	"PRODUCT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"PRODUCT_NAME" varchar(500) NOT NULL,
	"PRODUCT_DESCRIPTION" json NOT NULL,
	"PRODUCT_IMAGE" text NOT NULL,
	"PRODUCT_QUANTITY" int4 NOT NULL,
	"PRODUCT_PRICE" numeric(10, 2) NOT NULL,
	"CREATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"PRODUCT_CATEGORY" varchar(50) NOT NULL,
	"GENDER" varchar(10) NOT NULL,
	"AVERAGE_RATING" numeric(3, 2) NULL,
	CONSTRAINT "PRODUCT_pkey" PRIMARY KEY ("PRODUCT_ID")
);
