package isomessage

import (
	"github.com/moov-io/iso8583"
	"github.com/moov-io/iso8583/encoding"
	"github.com/moov-io/iso8583/field"
	"github.com/moov-io/iso8583/padding"
	"github.com/moov-io/iso8583/prefix"
)

// special

// 0: field.NewString(&field.Spec{
// 	Length:      4,
// 	Description: "Message Type Indicator",
// 	Enc:         encoding.ASCII,
// 	Pref:        prefix.ASCII.Fixed,
//
// }),
// // field 1 ok
// 1: field.NewBitmap(&field.Spec{
// 	Description: "Bitmap",
// 	Enc:         encoding.BytesToASCIIHex,
// 	Pref:        prefix.Hex.Fixed,
// }),

var Spec = &iso8583.MessageSpec{
	Fields: map[int]field.Field{
		0: field.NewString(&field.Spec{
			Length:      4,
			Description: "Message Type Indicator",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		// field 1 ok
		1: field.NewBitmap(&field.Spec{
			Description: "Bitmap",
			Enc:         encoding.BytesToASCIIHex,
			Pref:        prefix.Hex.Fixed,
		}),
		2: field.NewString(&field.Spec{
			Length:      19,
			Description: "PAN - PRIMARY ACCOUNT NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		3: field.NewString(&field.Spec{
			Length:      6,
			Description: "PROCESSING CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		4: field.NewString(&field.Spec{
			Length:      12,
			Description: "AMOUNT,TRANSACTION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		5: field.NewString(&field.Spec{
			Length:      12,
			Description: "AMOUNT,SETTLEMENT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		6: field.NewString(&field.Spec{
			Length:      12,
			Description: "AMOUNT,CARDHOLDER BILLING",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		7: field.NewString(&field.Spec{
			Length:      10,
			Description: "TRANSMISSION DATE AND TIME",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		8: field.NewString(&field.Spec{
			Length:      8,
			Description: "AMOUNT,CARDHOLDER BILLING FEE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		9: field.NewString(&field.Spec{
			Length:      8,
			Description: "CONVERSION RATE,SETTLEMENT,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		10: field.NewString(&field.Spec{
			Length:      8,
			Description: "CONVERSION RATE,CARDHOLDER BILLING",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		11: field.NewString(&field.Spec{
			Length:      6,
			Description: "SYSTEM TRACE AUDIT NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		12: field.NewString(&field.Spec{
			Length:      6,
			Description: "TIME,LOCAL TRANSACTION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		13: field.NewString(&field.Spec{
			Length:      4,
			Description: "DATE,LOCAL TRANSACTION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		14: field.NewString(&field.Spec{
			Length:      4,
			Description: "DATE,EXPIRATION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		15: field.NewString(&field.Spec{
			Length:      4,
			Description: "DATE,SETTLEMENT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		16: field.NewString(&field.Spec{
			Length:      4,
			Description: "DATE,CONVERSION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		17: field.NewString(&field.Spec{
			Length:      4,
			Description: "DATE,CAPTURE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		18: field.NewString(&field.Spec{
			Length:      4,
			Description: "MERCHANTS TYPE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		19: field.NewString(&field.Spec{
			Length:      3,
			Description: "ACQUIRING INSTITUTION COUNTRY CODE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		20: field.NewString(&field.Spec{
			Length:      3,
			Description: "PAN EXTENDED COUNTRY CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		21: field.NewString(&field.Spec{
			Length:      3,
			Description: "FORWARDING INSTITUTION COUNTRY CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		22: field.NewString(&field.Spec{
			Length:      3,
			Description: "POINT OF SERVICE ENTRY MODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		23: field.NewString(&field.Spec{
			Length:      3,
			Description: "CARD SEQUENCE NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		24: field.NewString(&field.Spec{
			Length:      3,
			Description: "NETWORK INTERNATIONAL IDENTIFIEER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		25: field.NewString(&field.Spec{
			Length:      2,
			Description: "POINT OF SERVICE CONDITION CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		26: field.NewString(&field.Spec{
			Length:      2,
			Description: "POINT OF SERVICE PIN CAPTURE CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		27: field.NewString(&field.Spec{
			Length:      1,
			Description: "AUTHORIZATION IDENTIFICATION RESP LEN",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		28: field.NewString(&field.Spec{
			Length:      9,
			Description: "AMOUNT,TRANSACTION FEE",
			Enc:         encoding.ASCII,
		}),
		29: field.NewString(&field.Spec{
			Length:      9,
			Description: "AMOUNT,SETTLEMENT FEE,",
			Enc:         encoding.ASCII,
		}),
		30: field.NewString(&field.Spec{
			Length:      9,
			Description: "AMOUNT,TRANSACTION PROCESSING FEE",
			Enc:         encoding.ASCII,
		}),
		31: field.NewString(&field.Spec{
			Length:      9,
			Description: "AMOUNT,SETTLEMENT PROCESSING FEE",
			Enc:         encoding.ASCII,
		}),
		32: field.NewString(&field.Spec{
			Length:      11,
			Description: "ACQUIRING INSTITUTION IDENT CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		33: field.NewString(&field.Spec{
			Length:      11,
			Description: "FORWARDING INSTITUTION IDENT CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		34: field.NewString(&field.Spec{
			Length:      28,
			Description: "PAN EXTENDED",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		35: field.NewString(&field.Spec{
			Length:      37,
			Description: "TRACK 2 DATA",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		36: field.NewString(&field.Spec{
			Length:      104,
			Description: "TRACK 3 DATA",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		37: field.NewString(&field.Spec{
			Length:      12,
			Description: "RETRIEVAL REFERENCE NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		38: field.NewString(&field.Spec{
			Length:      6,
			Description: "AUTHORIZATION IDENTIFICATION RESPONSE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		39: field.NewString(&field.Spec{
			Length:      2,
			Description: "RESPONSE CODE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		40: field.NewString(&field.Spec{
			Length:      3,
			Description: "SERVICE RESTRICTION CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		41: field.NewString(&field.Spec{
			Length:      8,
			Description: "CARD ACCEPTOR TERMINAL IDENTIFICACION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		42: field.NewString(&field.Spec{
			Length:      15,
			Description: "CARD ACCEPTOR IDENTIFICATION CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		43: field.NewString(&field.Spec{
			Length:      40,
			Description: "CARD ACCEPTOR NAME/LOCATION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		44: field.NewString(&field.Spec{
			Length:      25,
			Description: "ADITIONAL RESPONSE DATA",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		45: field.NewString(&field.Spec{
			Length:      76,
			Description: "TRACK 1 DATA",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		46: field.NewString(&field.Spec{
			Length:      999,
			Description: "ADITIONAL DATA - ISO",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		47: field.NewString(&field.Spec{
			Length:      999,
			Description: "ADITIONAL DATA - NATIONAL",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		48: field.NewString(&field.Spec{
			Length:      999,
			Description: "ADITIONAL DATA - PRIVATE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		49: field.NewString(&field.Spec{
			Length:      3,
			Description: "CURRENCY CODE,TRANSACTION,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		50: field.NewString(&field.Spec{
			Length:      3,
			Description: "CURRENCY CODE,SETTLEMENT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		51: field.NewString(&field.Spec{
			Length:      3,
			Description: "CURRENCY CODE,CARDHOLDER BILLING",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		52: field.NewString(&field.Spec{
			Length:      16,
			Description: "PIN DATA",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		53: field.NewString(&field.Spec{
			Length:      8,
			Description: "SECURITY RELATED CONTROL INFORMATION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		54: field.NewString(&field.Spec{
			Length:      120,
			Description: "ADDITIONAL AMOUNTS",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		55: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		56: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		57: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		58: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		59: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		60: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		61: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		62: field.NewString(&field.Spec{
			Length:      10,
			Description: "RESERVED PRIVATE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		63: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		64: field.NewBinary(&field.Spec{
			Length:      8,
			Description: "MESSAGE AUTHENTICATION CODE FIELD",
			Enc:         encoding.Binary,
			Pref:        prefix.ASCII.Fixed,
		}),
		65: field.NewBinary(&field.Spec{
			Length:      1,
			Description: "BITMAP,EXTENDED",
			Enc:         encoding.Binary,
			Pref:        prefix.ASCII.Fixed,
		}),
		66: field.NewString(&field.Spec{
			Length:      1,
			Description: "SETTLEMENT CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		67: field.NewString(&field.Spec{
			Length:      2,
			Description: "EXTENDED PAYMENT CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		68: field.NewString(&field.Spec{
			Length:      3,
			Description: "RECEIVING INSTITUTION COUNTRY CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		69: field.NewString(&field.Spec{
			Length:      3,
			Description: "SETTLEMENT INSTITUTION COUNTRY CODE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		70: field.NewString(&field.Spec{
			Length:      3,
			Description: "NETWORK MANAGEMENT INFORMATION CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		71: field.NewString(&field.Spec{
			Length:      4,
			Description: "MESSAGE NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		72: field.NewString(&field.Spec{
			Length:      4,
			Description: "MESSAGE NUMBER LAST",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		73: field.NewString(&field.Spec{
			Length:      6,
			Description: "DATE ACTION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		74: field.NewString(&field.Spec{
			Length:      10,
			Description: "CREDITS NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		75: field.NewString(&field.Spec{
			Length:      10,
			Description: "CREDITS REVERSAL NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		76: field.NewString(&field.Spec{
			Length:      10,
			Description: "DEBITS NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		77: field.NewString(&field.Spec{
			Length:      10,
			Description: "DEBITS REVERSAL NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		78: field.NewString(&field.Spec{
			Length:      10,
			Description: "TRANSFER NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		79: field.NewString(&field.Spec{
			Length:      10,
			Description: "TRANSFER REVERSAL NUMBER,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		80: field.NewString(&field.Spec{
			Length:      10,
			Description: "INQUIRIES NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		81: field.NewString(&field.Spec{
			Length:      10,
			Description: "AUTHORIZATION NUMBER",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		82: field.NewString(&field.Spec{
			Length:      12,
			Description: "CREDITS,PROCESSING FEE AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		83: field.NewString(&field.Spec{
			Length:      12,
			Description: "CREDITS,TRANSACTION FEE AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		84: field.NewString(&field.Spec{
			Length:      12,
			Description: "DEBITS,PROCESSING FEE AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		85: field.NewString(&field.Spec{
			Length:      12,
			Description: "DEBITS,TRANSACTION FEE AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		86: field.NewString(&field.Spec{
			Length:      16,
			Description: "CREDITS,AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		87: field.NewString(&field.Spec{
			Length:      16,
			Description: "CREDITS,REVERSAL AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		88: field.NewString(&field.Spec{
			Length:      16,
			Description: "DEBITS,AMOUNT",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		89: field.NewString(&field.Spec{
			Length:      16,
			Description: "DEBITS,REVERSAL AMOUNT,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		90: field.NewString(&field.Spec{
			Length:      42,
			Description: "ORIGINAL DATA ELEMENTS",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		91: field.NewString(&field.Spec{
			Length:      1,
			Description: "FILE UPDATE CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		92: field.NewString(&field.Spec{
			Length:      2,
			Description: "FILE SECURITY CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		93: field.NewString(&field.Spec{
			Length:      6,
			Description: "RESPONSE INDICATOR",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		94: field.NewString(&field.Spec{
			Length:      7,
			Description: "SERVICE INDICATOR",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		95: field.NewString(&field.Spec{
			Length:      42,
			Description: "REPLACEMENT AMOUNTS",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
		}),
		96: field.NewBinary(&field.Spec{
			Length:      16,
			Description: "MESSAGE SECURITY CODE",
			Enc:         encoding.Binary,
			Pref:        prefix.ASCII.Fixed,
		}),
		97: field.NewString(&field.Spec{
			Length:      17,
			Description: "AMOUNT,NET SETTLEMENT",
			Enc:         encoding.ASCII,
		}),
		98: field.NewString(&field.Spec{
			Length:      25,
			Description: "PAYEE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
		99: field.NewString(&field.Spec{
			Length:      11,
			Description: "SETTLEMENT INSTITUTION IDENT CODE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		100: field.NewString(&field.Spec{
			Length:      11,
			Description: "RECEIVING INSTITUTION IDENT CODE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		101: field.NewString(&field.Spec{
			Length:      17,
			Description: "FILE NAME",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		102: field.NewString(&field.Spec{
			Length:      28,
			Description: "ACCOUNT IDENTIFICATION 1",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		103: field.NewString(&field.Spec{
			Length:      28,
			Description: "ACCOUNT IDENTIFICATION 2",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LL,
		}),
		104: field.NewString(&field.Spec{
			Length:      210,
			Description: "TRANSACTION DESCRIPTION",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		105: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		106: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		107: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		108: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		109: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		110: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		111: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED ISO USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		112: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		113: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		114: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		115: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		116: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		117: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		118: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		119: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED NATIONAL USE,",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		120: field.NewString(&field.Spec{
			Length:      70,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		121: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		122: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		123: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		124: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		125: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		126: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		127: field.NewString(&field.Spec{
			Length:      999,
			Description: "RESERVED PRIVATE USE",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.LLL,
		}),
		128: field.NewString(&field.Spec{
			Length:      64,
			Description: "MAC 2 };",
			Enc:         encoding.ASCII,
			Pref:        prefix.ASCII.Fixed,
			Pad:         padding.Right(' '),
		}),
	},
}
