CREATE TABLE public."PRODUCT" (
	"PRODUCT_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"PRODUCT_NAME" varchar(500) NOT NULL,
	"PRODUCT_DESCRIPTION" json NOT NULL,
	"PRODUCT_IMAGE" text NOT NULL,
	"PRODUCT_QUANTITY" int4 NOT NULL,
	"PRODUCT_PRICE" numeric(10, 2) NOT NULL,
	"CREATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "PRODUCT_pkey" PRIMARY KEY ("PRODUCT_ID")
);

CREATE TABLE public."PRODUCT_CATEGORY" (
	"CATEGORY_ID" uuid NOT NULL DEFAULT gen_random_uuid(),
	"PRODUCT_ID" uuid NOT NULL,
	"CATEGORY_NAME" varchar(50) NOT NULL,
	"CREATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "PRODUCT_CATEGORY_pkey" PRIMARY KEY ("CATEGORY_ID")
);