# Required properties
sonar.projectVersion=1.0

# Path to the source files
sonar.sources=./

# Language
sonar.language=go

# Test coverage report
sonar.go.coverage.reportPaths=coverage.out

# Optional properties
sonar.exclusions=**/*_test.go
sonar.test.inclusions=./internal/usecase/*/*_test.go