package domain

const (
	REDIS_KEY_GET_ALL_PRODUCTS = "PRODUCTS_ALL"
	REDIS_KEY_PRODUCT_ID       = "PRODUCT_ID-"
	REDIS_KEY_GENDER           = "PRODUCT_GENDER_"
	REDIS_KEY_CATEGORY         = "PRODUCT_CATEGORY_"
	REDIS_KEY_PRODUCT_DETAIL   = "PRODUCT_DETAIL-"
)
