syntax = "proto3";

package authentication;

option go_package="authentication-proto";

message CreateTokenRequest {
    string useID = 1;
}

message CreateTokenResponse {
    string token = 1;
}

message VerifyTokenRequest {
    string token = 1;
}

message VerifyTokenResponse {
    bool valid = 1;
    string userID = 2;
}

service AuthenticationService {
    rpc CreateToken(CreateTokenRequest) returns (CreateTokenResponse) {}
    rpc VerifyToken(VerifyTokenRequest) returns (VerifyTokenResponse) {}
}