CREATE TABLE public."COMMENT" (
    "COMMENT_ID" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "PRODUCT_ID" UUID NOT NULL,
    "USER_ID" UUID NOT NULL,
    "REVIEW_EVALUATION" INT NOT NULL,
    "REVIEW_DETAIL" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
