// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/is/v1/cart-service/add": {
            "post": {
                "description": "Insert into cart values ...",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CART SERVICE"
                ],
                "summary": "AddCartItem",
                "operationId": "AddCartItem",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_cart_AddCartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_cart_AddCartItemResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/cart-service/delete-cart-item": {
            "post": {
                "description": "giving the cartITemID delete the cartItem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CART SERVICE"
                ],
                "summary": "DeleteCartItem",
                "operationId": "DeleteCartItem",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_cart_DeleteCartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_cart_DeleteCartItemResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/cart-service/delete-user-cart": {
            "post": {
                "description": "delete all the record in table cart with corresponding userID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CART SERVICE"
                ],
                "summary": "DeleteUserCart",
                "operationId": "DeleteUserCart",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_cart_DeleteUserCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_cart_DeleteUserCartResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/cart-service/get-items": {
            "post": {
                "description": "select * from cart where userID = :1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CART SERVICE"
                ],
                "summary": "GetCart",
                "operationId": "GetCart",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_cart_GetCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_cart_GetCartResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/cart-service/update": {
            "post": {
                "description": "Update the quantity of an item in the cart. front end receives ok returns then update StateQuantity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CART SERVICE"
                ],
                "summary": "UpdateCartItem",
                "operationId": "UpdateCartItem",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_cart_UpdateCartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_cart_UpdateCartItemResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/comment-service/add": {
            "post": {
                "description": "insert into table comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMENT SERVICE"
                ],
                "summary": "AddComment",
                "operationId": "AddComment",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_comment_AddCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_comment_AddCommentResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/comment-service/get-comment": {
            "post": {
                "description": "select * from table comment where productID = :1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COMMENT SERVICE"
                ],
                "summary": "GetComment",
                "operationId": "GetComment",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_comment_GetCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_comment_GetCommentResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/order-service/checkout": {
            "post": {
                "description": "Delete all items on cart -\u003e minus quantity of product in cart service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "Checkout",
                "operationId": "Checkout",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-handlers_CheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-handlers_CheckoutResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/order-service/get-checkout-item": {
            "post": {
                "description": "Get the checkout item (cdc from cart table)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "GetCheckoutItem",
                "operationId": "GetCheckoutItem",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-handlers_GetCheckoutItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-handlers_GetCheckoutItemResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/order-service/get-history": {
            "post": {
                "description": "Show a history of purchased products from a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ORDER SERVICE"
                ],
                "summary": "GetPurchasedProducts",
                "operationId": "GetPurchasedProducts",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-handlers_GetPurchasedProductsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-handlers_GetPurchasedProductsResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/product-service/get-product-detail": {
            "post": {
                "description": "Get the detail of a product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "GetProductDetail",
                "operationId": "GetProductDetail",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_product_GetProductDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_product_GetProductDetailResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/product-service/get-products": {
            "post": {
                "description": "list all the products in the inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "GetAllProduct",
                "operationId": "GetAllProduct",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_product_GetAllProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_product_GetAllProductResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/user-service/get-product-detail": {
            "post": {
                "description": "Update the user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER SERVICE"
                ],
                "summary": "UpdateUserInformation",
                "operationId": "UpdateUserInformation",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_user_UpdateUserInformationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_user_UpdateUserInformationResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/user-service/login": {
            "post": {
                "description": "login for a new session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER SERVICE"
                ],
                "summary": "Login",
                "operationId": "Login",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_user_LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_user_LoginResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/user-service/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER SERVICE"
                ],
                "summary": "RegisterUser",
                "operationId": "RegisterUser",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_user_RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_user_RegisterResponse"
                        }
                    }
                }
            }
        },
        "/is/v1/user-service/update": {
            "post": {
                "description": "Get the user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "USER SERVICE"
                ],
                "summary": "GetUserInformation",
                "operationId": "GetUserInformation",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.Request-github_com_kingstonduy_api-document_domain_user_GetUserInformationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/transport.Response-github_com_kingstonduy_api-document_domain_user_GetUserInformationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kingstonduy_api-document_domain_cart.AddCartItemDetail": {
            "type": "object",
            "properties": {
                "cartItemQuantity": {
                    "type": "integer"
                },
                "productId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.AddCartItemRequest": {
            "type": "object",
            "properties": {
                "cartItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.AddCartItemDetail"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.AddCartItemResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_cart.DeleteCartItemRequest": {
            "type": "object",
            "properties": {
                "cartItemID": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.DeleteCartItemResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_cart.DeleteUserCartRequest": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.DeleteUserCartResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_cart.GetCartItemDetail": {
            "type": "object",
            "properties": {
                "cartItemId": {
                    "type": "string"
                },
                "cartItemQuantity": {
                    "type": "integer"
                },
                "productCatergory": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "productPrice": {
                    "type": "number"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.GetCartRequest": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.GetCartResponse": {
            "type": "object",
            "properties": {
                "cartItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.GetCartItemDetail"
                    }
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.UpdateCartItemRequest": {
            "type": "object",
            "properties": {
                "cartItemId": {
                    "type": "string"
                },
                "cartItemQuantity": {
                    "type": "integer"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_cart.UpdateCartItemResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_comment.AddCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "productId",
                "rating",
                "userId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_comment.AddCommentResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_comment.GetCommentRequest": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_comment.GetCommentResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_product.GetAllProductRequest": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_product.GetAllProductResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_product.Product"
                    }
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_product.GetProductDetailRequest": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_product.GetProductDetailResponse": {
            "type": "object",
            "properties": {
                "productCatergory": {
                    "type": "string"
                },
                "productDescription": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "productPrice": {
                    "type": "number"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_product.Product": {
            "type": "object",
            "properties": {
                "averageRating": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.GetUserInformationRequest": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.GetUserInformationResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "cityCode": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "districtCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "ward": {
                    "type": "string"
                },
                "wardCode": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.LoginResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_user.RegisterRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "cityCode": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "districtCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "ward": {
                    "type": "string"
                },
                "wardCode": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.RegisterResponse": {
            "type": "object"
        },
        "github_com_kingstonduy_api-document_domain_user.UpdateUserInformationRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "cityCode": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "districtCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "ward": {
                    "type": "string"
                },
                "wardCode": {
                    "type": "string"
                }
            }
        },
        "github_com_kingstonduy_api-document_domain_user.UpdateUserInformationResponse": {
            "type": "object"
        },
        "handlers.CheckoutDetail": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "handlers.CheckoutRequest": {
            "type": "object",
            "properties": {
                "checkoutDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CheckoutDetail"
                    }
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "handlers.CheckoutResponse": {
            "type": "object"
        },
        "handlers.GetCheckoutItemDetail": {
            "type": "object",
            "properties": {
                "pricePerUnit": {
                    "type": "number"
                },
                "productCatergory": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "productQuantity": {
                    "type": "integer"
                }
            }
        },
        "handlers.GetCheckoutItemRequest": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "handlers.GetCheckoutItemResponse": {
            "type": "object",
            "properties": {
                "checkoutItemDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GetCheckoutItemDetail"
                    }
                }
            }
        },
        "handlers.GetPurchasedProductsRequest": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "handlers.GetPurchasedProductsResponse": {
            "type": "object",
            "properties": {
                "purchasedProducts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PurchasedProductDetail"
                    }
                }
            }
        },
        "handlers.PurchasedProductDetail": {
            "type": "object",
            "properties": {
                "deliveryStatus": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "paymentStatus": {
                    "type": "string"
                },
                "productId": {
                    "type": "string"
                },
                "productImage": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_cart_AddCartItemRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.AddCartItemRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_cart_DeleteCartItemRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.DeleteCartItemRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_cart_DeleteUserCartRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.DeleteUserCartRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_cart_GetCartRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.GetCartRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_cart_UpdateCartItemRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.UpdateCartItemRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_comment_AddCommentRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_comment.AddCommentRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_comment_GetCommentRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_comment.GetCommentRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_product_GetAllProductRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_product.GetAllProductRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_product_GetProductDetailRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_product.GetProductDetailRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_user_GetUserInformationRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.GetUserInformationRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_user_LoginRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.LoginRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_user_RegisterRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.RegisterRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-github_com_kingstonduy_api-document_domain_user_UpdateUserInformationRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.UpdateUserInformationRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-handlers_CheckoutRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.CheckoutRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-handlers_GetCheckoutItemRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.GetCheckoutItemRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Request-handlers_GetPurchasedProductsRequest": {
            "type": "object",
            "required": [
                "trace"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.GetPurchasedProductsRequest"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_cart_AddCartItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.AddCartItemResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_cart_DeleteCartItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.DeleteCartItemResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_cart_DeleteUserCartResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.DeleteUserCartResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_cart_GetCartResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.GetCartResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_cart_UpdateCartItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_cart.UpdateCartItemResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_comment_AddCommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_comment.AddCommentResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_comment_GetCommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_comment.GetCommentResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_product_GetAllProductResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_product.GetAllProductResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_product_GetProductDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_product.GetProductDetailResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_user_GetUserInformationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.GetUserInformationResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_user_LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.LoginResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_user_RegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.RegisterResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-github_com_kingstonduy_api-document_domain_user_UpdateUserInformationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_kingstonduy_api-document_domain_user.UpdateUserInformationResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-handlers_CheckoutResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.CheckoutResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-handlers_GetCheckoutItemResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.GetCheckoutItemResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Response-handlers_GetPurchasedProductsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.GetPurchasedProductsResponse"
                },
                "result": {
                    "$ref": "#/definitions/transport.Result"
                },
                "trace": {
                    "$ref": "#/definitions/transport.Trace"
                }
            }
        },
        "transport.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "transport.Trace": {
            "type": "object",
            "required": [
                "cid",
                "cts"
            ],
            "properties": {
                "cid": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "cts": {
                    "type": "integer"
                },
                "dur": {
                    "type": "integer"
                },
                "frm": {
                    "type": "string"
                },
                "replyTo": {
                    "type": "string"
                },
                "sid": {
                    "type": "string"
                },
                "sts": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                },
                "transactionTimeout": {
                    "type": "integer",
                    "maximum": 120000
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
