definitions:
  domain.ExecuteTransactionRequest:
    properties:
      details:
        items:
          $ref: '#/definitions/domain.ExecuteTransactionRequestDetail'
        type: array
      userID:
        type: string
    type: object
  domain.ExecuteTransactionRequestDetail:
    properties:
      cartItemQuantity:
        type: integer
      productId:
        type: string
    type: object
  domain.ExecuteTransactionResponse:
    type: object
  domain.GetAllProductRequest:
    type: object
  domain.GetAllProductResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/domain.Product'
        type: array
    type: object
  domain.GetProductDetailRequest:
    properties:
      productId:
        type: string
    type: object
  domain.GetProductDetailResponse:
    properties:
      productCatergory:
        type: string
      productDescription:
        type: string
      productId:
        type: string
      productImage:
        type: string
      productName:
        type: string
      productPrice:
        type: number
      productQuantity:
        type: integer
    type: object
  domain.Product:
    properties:
      averageRating:
        type: number
      productId:
        type: string
      productImage:
        type: string
      productName:
        type: string
      productPrice:
        type: number
      productQuantity:
        type: integer
    type: object
  domain.RevertTransactionRequest:
    properties:
      details:
        items:
          $ref: '#/definitions/domain.RevertTransactionRequestDetail'
        type: array
      userID:
        type: string
    type: object
  domain.RevertTransactionRequestDetail:
    properties:
      cartItemQuantity:
        type: integer
      productId:
        type: string
    type: object
  domain.RevertTransactionResponse:
    type: object
  transport.Request-domain_ExecuteTransactionRequest:
    properties:
      data:
        $ref: '#/definitions/domain.ExecuteTransactionRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Request-domain_GetAllProductRequest:
    properties:
      data:
        $ref: '#/definitions/domain.GetAllProductRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Request-domain_GetProductDetailRequest:
    properties:
      data:
        $ref: '#/definitions/domain.GetProductDetailRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Request-domain_RevertTransactionRequest:
    properties:
      data:
        $ref: '#/definitions/domain.RevertTransactionRequest'
      trace:
        $ref: '#/definitions/transport.Trace'
    required:
    - trace
    type: object
  transport.Response-domain_ExecuteTransactionResponse:
    properties:
      data:
        $ref: '#/definitions/domain.ExecuteTransactionResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Response-domain_GetAllProductResponse:
    properties:
      data:
        $ref: '#/definitions/domain.GetAllProductResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Response-domain_GetProductDetailResponse:
    properties:
      data:
        $ref: '#/definitions/domain.GetProductDetailResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Response-domain_RevertTransactionResponse:
    properties:
      data:
        $ref: '#/definitions/domain.RevertTransactionResponse'
      result:
        $ref: '#/definitions/transport.Result'
      trace:
        $ref: '#/definitions/transport.Trace'
    type: object
  transport.Result:
    properties:
      code:
        type: string
      details:
        type: object
      message:
        type: string
      statusCode:
        type: integer
    type: object
  transport.Trace:
    properties:
      cid:
        type: string
      clientId:
        type: string
      cts:
        type: integer
      dur:
        type: integer
      frm:
        type: string
      replyTo:
        type: string
      sid:
        type: string
      sts:
        type: integer
      to:
        type: string
      transactionTimeout:
        maximum: 120000
        type: integer
      userName:
        type: string
    required:
    - cid
    - cts
    type: object
info:
  contact: {}
paths:
  /is/v1/product-service/execute-transaction:
    post:
      consumes:
      - application/json
      description: remove the product quantity from the inventory
      operationId: ExecuteTransaction
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_ExecuteTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_ExecuteTransactionResponse'
      summary: ExecuteTransaction
      tags:
      - PRODUCT
  /is/v1/product-service/get-product-detail:
    post:
      consumes:
      - application/json
      description: Get the detail of a product
      operationId: GetProductDetail
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_GetProductDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_GetProductDetailResponse'
      summary: GetProductDetail
      tags:
      - PRODUCT
  /is/v1/product-service/get-products:
    post:
      consumes:
      - application/json
      description: list all the products in the inventory
      operationId: GetAllProduct
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_GetAllProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_GetAllProductResponse'
      summary: GetAllProduct
      tags:
      - PRODUCT
  /is/v1/product-service/revert-transaction:
    post:
      consumes:
      - application/json
      description: revert the transaction
      operationId: RevertTransaction
      parameters:
      - description: Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/transport.Request-domain_RevertTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/transport.Response-domain_RevertTransactionResponse'
      summary: RevertTransaction
      tags:
      - PRODUCT
swagger: "2.0"
